name: arcane-otx
version: 1.1.0
license: BSD-2-Clause
author:
  name: Conor Quigley
  url: https://konundrum.org/

genopts:
  dotstorm: true

# Defines required role permissions.
perms:
  - perm: [otx, user]
    desc: Controls user access to Arcane OTX pkg.
    gate: cortex

docs:
  - content: |
      This package provides Alienvault OTX API support for Synapse.
      This pkg is in development and is not stable.
    title: Arcane Observatory Synapse OTX Package.

modules:
  - name: arcane.otx
  - name: arcane.otx.setup
  - name: arcane.otx.ingest
    modconf:
      # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      # FOR THE LOVE OF ALL THAT IS HOLY, SET THIS
      # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
      source: <GUID>
      ioc_limit: &ioc_limit 200
  - name: arcane.otx.api
    asroot:perms:
      - [otx, user]
    modconf:
      api_url: https://otx.alienvault.com/api/v1

commands:
  - name: otx.setup.apikey
    descr: Setup Arcane Observatory OTX API Key
    # Do not allow to run as root.
    asroot: False
    # User perms required to acces this command?
    perms:
      - [otx, user]
    cmdargs:
      - - apikey
        - type: str
          help: Alienvault OTX Key.

      - - --debug
        - default: false
          action: store_true
          help: Show verbose debug output.
          type: bool

      - - --timeout
        - default: 0
          type: int
          help: Specify a timeout in seconds.

  - name: otx.sync
    descr: Sync OTX subscribed pulses
    # Do not allow to run as root.
    asroot: False
    # User perms required to acces this command?
    perms:
      - [otx, user]
    cmdargs:
      - - --since
        - type: str
          default: "-1 days"
          help: |
            Specify a modified since value. E.g.: "-1 days" "2022-03-01T00:00:00Z"

      - - --debug
        - default: false
          action: store_true
          help: Show verbose debug output.
          type: bool

      - - --timeout
        - default: 0
          type: int
          help: Specify a timeout in seconds.
    forms:
      output:
        - media:news

  - name: otx.pulse
    descr: Retrieve a specific pulse.
    # Do not allow to run as root.
    asroot: False
    # User perms required to acces this command?
    perms:
      - [otx, user]
    cmdargs:
      - - pulseid
        - type: str
          help: OTX Pulse ID

      - - --debug
        - default: false
          action: store_true
          help: Show verbose debug output.
          type: bool

      - - --timeout
        - default: 0
          type: int
          help: Specify a timeout in seconds.

      - - --iocs
        - default: false
          action: store_true
          # https://otx.alienvault.com/pulse/62637949a39428085f129938
          help: Retrieve indicators? Some pulses are huge and not worth pulling in 60,000 IPs.
          type: bool

      - - --ioc_limit
        - default: *ioc_limit
          type: int
          # https://otx.alienvault.com/pulse/62637949a39428085f129938
          help: Set pulse IOCs size limit. Ignore pulses with indicators largers than this total.
    forms:
      output:
        - media:news

  - name: otx.domain
    descr: Enrich an FQDN from Alienvault OTX Domain API Endpoint.
    asroot: False
    cmdargs:
      - - --debug
        - default: false
          action: store_true
          help: Show verbose debug output.
          type: bool

      - - --yield
        - default: false
          action: store_true
          help: Yield the newly created nodes.

      - - --timeout
        - default: 0
          type: int
          help: Specify a timeout in seconds.
    perms:
      - [otx, user]
    forms:
      input:
        - inet:fqdn
      output:
        - inet:fqdn

  - name: otx.ip
    descr: Enrich an IP address from Alienvault OTX Domain API Endpoint.
    asroot: False
    cmdargs:
      - - --debug
        - default: false
          action: store_true
          help: Show verbose debug output.
          type: bool

      - - --yield
        - default: false
          action: store_true
          help: Yield the newly created nodes.

      - - --timeout
        - default: 0
          type: int
          help: Specify a timeout in seconds.
    perms:
      - [otx, user]
    forms:
      input:
        - inet:ipv4
        - inet:ipv6
      output:
        - inet:ipv4
        - inet:ipv6

  - name: otx.pdns
    descr: Passive DNS data from OTX. Supports inet:fqdn, inet:ipv4 and inet:ipv6
    asroot: False
    cmdargs:
      - - --debug
        - default: false
          action: store_true
          help: Show verbose debug output.
          type: bool

      - - --yield
        - default: false
          action: store_true
          help: Yield the newly created nodes.

      - - --timeout
        - default: 0
          type: int
          help: Specify a timeout in seconds.
    perms:
      - [otx, user]
    forms:
      input:
        - inet:fqdn
        - inet:ipv4
        - inet:ipv6
      output:
        - inet:fqdn
        - inet:ipv4
        - inet:ipv6

